import { Product } from "@/components/data-table/Columns";

export const products: Product[] = [
	{
		SKU: 564339,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title:
			"Gift Set -- 4.2 oz Eau De Toilette Spray + .67 oz Mini EDT Spray + 3.4 oz After Shave Balm + 3.4 oz Body Wash",
		Gender: "Men",
		RETAIL: null,
		"Cost Price": 39.5,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/ObsCTP.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 19,
		size: "--",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 429247,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "Eau De Toilette Spray 200 ml",
		Gender: "Men",
		RETAIL: 102,
		"Cost Price": 23.85,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OBSMCS67.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 500,
		size: "200 ml",
		UPC: 88300106752,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400028,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "Eau De Toilette Spray 75 ml",
		Gender: "Men",
		RETAIL: 62,
		"Cost Price": 15.63,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OBS75TSM.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 500,
		size: "75 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 446011,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "Eau De Toilette Spray (Tester) 120 ml",
		Gender: "Men",
		RETAIL: 82,
		"Cost Price": 12.87,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OM4T.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 500,
		size: "120 ml",
		UPC: 88300196517,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 533144,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "Eau De Toilette Spray (unboxed) 200 ml",
		Gender: "Men",
		RETAIL: null,
		"Cost Price": 31,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OM67TSU.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 2,
		size: "200 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 459524,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "After Shave Balm 150 ml",
		Gender: "Men",
		RETAIL: 84,
		"Cost Price": 21.35,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OMASB5.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 500,
		size: "150 ml",
		UPC: 88300166152,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400038,
		Name: "Obsession by Calvin Klein",
		Description:
			"Launched by the design house of Calvin Klein in 1986, Obsession is classified as a refreshing, oriental, woody fragrance.This masculine scent possesses a blend of lavender, mandarin, clove, nutmeg and amber. It is recommended for office wear.",
		Brand: "Calvin Klein",
		Title: "Eau De Toilette Spray 120 ml",
		Gender: "Men",
		RETAIL: 82,
		"Cost Price": 17.07,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/M140256O.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-cologne?src=drpshp",
		Quantity: 500,
		size: "120 ml",
		UPC: 88300106516,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400042,
		Name: "Obsession by Calvin Klein",
		Description:
			"This fragrance was created by the design house of Calvin Klein with perfumer Jean Guichard and released in 1985.  This is a remarkable oriental spicy perfume with a fresh take especially for women.  The blend will offer you a very sensual experience.",
		Brand: "Calvin Klein",
		Title: "Eau De Parfum Spray 100 ml",
		Gender: "Women",
		RETAIL: 92,
		"Cost Price": 18.51,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/W160628O.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-perfume?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 88300103409,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 447164,
		Name: "Obsession by Calvin Klein",
		Description:
			"This fragrance was created by the design house of Calvin Klein with perfumer Jean Guichard and released in 1985.  This is a remarkable oriental spicy perfume with a fresh take especially for women.  The blend will offer you a very sensual experience.",
		Brand: "Calvin Klein",
		Title: "Eau De Parfum Spray (Tester) 100 ml",
		Gender: "Women",
		RETAIL: 92,
		"Cost Price": 15.28,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OWP34T.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-perfume?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 88300193400,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 446330,
		Name: "Obsession by Calvin Klein",
		Description:
			"This fragrance was created by the design house of Calvin Klein with perfumer Jean Guichard and released in 1985.  This is a remarkable oriental spicy perfume with a fresh take especially for women.  The blend will offer you a very sensual experience.",
		Brand: "Calvin Klein",
		Title:
			"Gift Set -- 3.4 oz Eau De Parfum Spray + 6.7 oz Body Lotion + .5 oz Mini EDP Spray",
		Gender: "Women",
		RETAIL: 78,
		"Cost Price": 39.9,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OWGS3P.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-perfume?src=drpshp",
		Quantity: 500,
		size: "--",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400050,
		Name: "Obsession by Calvin Klein",
		Description:
			"This fragrance was created by the design house of Calvin Klein with perfumer Jean Guichard and released in 1985.  This is a remarkable oriental spicy perfume with a fresh take especially for women.  The blend will offer you a very sensual experience.",
		Brand: "Calvin Klein",
		Title: "Eau De Parfum Spray 50 ml",
		Gender: "Women",
		RETAIL: 73,
		"Cost Price": 16.09,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OBS50PSW.jpg",
		URL: "https://www.fragrancex.com/products/calvin-klein/obsession-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: 88300103300,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 423316,
		Name: "Ocean Dream by Designer Parfums Ltd",
		Description:
			"This phenomenal cologne was created by Designer Parfums, in 2005. Its fantastic scent includes the mixture of sandalwood, heliotrope, orange, and lily.",
		Brand: "Designer Parfums Ltd",
		Title: "Eau De Toilette Spray 100 ml",
		Gender: "Men",
		RETAIL: 55,
		"Cost Price": 11.7,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OCEDMTS34.jpg",
		URL: "https://www.fragrancex.com/products/designer-parfums-ltd/ocean-dream-cologne?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 5050456000197,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400068,
		Name: "Ocean Dream by Designer Parfums Ltd",
		Description:
			"Launched by the design house of Giorgio Beverly Hills in 1996, Ocean Dream is classified as a refreshing, flowery fragrance. This feminine scent possesses a blend of waterflowers including sandalwood and orange blossom. Accompanied by the scent of the pure ocean air.",
		Brand: "Designer Parfums Ltd",
		Title: "Eau De Toilette Spray 90 ml",
		Gender: "Women",
		RETAIL: 59,
		"Cost Price": 22,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/ODRE90TSW.jpg",
		URL: "https://www.fragrancex.com/products/designer-parfums-ltd/ocean-dream-perfume?src=drpshp",
		Quantity: 500,
		size: "90 ml",
		UPC: 5050456000036,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 564278,
		Name: "One Man Show by Jacques Bogart",
		Description:
			"This fragrance was created by the house of Jacques Bogart  with perfumer Roger Pellegrino and released in 1980.  This timeless woodsy spicy cologne for men is simply gorgeous.  A complex blend of notes that creates an inspiring personality in this scent.",
		Brand: "Jacques Bogart",
		Title: "Body Spray 195 ml",
		Gender: "Men",
		RETAIL: null,
		"Cost Price": 3.38,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OneJM1.jpg",
		URL: "https://www.fragrancex.com/products/jacques-bogart/one-man-show-cologne?src=drpshp",
		Quantity: 500,
		size: "195 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400084,
		Name: "One Man Show by Jacques Bogart",
		Description:
			"This fragrance was created by the house of Jacques Bogart  with perfumer Roger Pellegrino and released in 1980.  This timeless woodsy spicy cologne for men is simply gorgeous.  A complex blend of notes that creates an inspiring personality in this scent.",
		Brand: "Jacques Bogart",
		Title: "Eau De Toilette Spray 100 ml",
		Gender: "Men",
		RETAIL: 32.5,
		"Cost Price": 8.38,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/M140260O.jpg",
		URL: "https://www.fragrancex.com/products/jacques-bogart/one-man-show-cologne?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 3355991000223,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400105,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Launched by the design house of Yves Saint Laurent in 1995, Opium is classified as a sharp, oriental, woody fragrance. This masculine scent possesses a blend of vanilla, ginger, pepper, and cedar. It is recommended for daytime wear.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Toilette Spray 100 ml",
		Gender: "Men",
		RETAIL: 108,
		"Cost Price": 106,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OPI100TSM.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-cologne?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 547630,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Parfum Spray (New Packaging) 90 ml",
		Gender: "Women",
		RETAIL: null,
		"Cost Price": 124,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/OPIYW3ED.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "90 ml",
		UPC: 3365440556263,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 461253,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Parfum Spray (New Packaging) 50 ml",
		Gender: "Women",
		RETAIL: 99,
		"Cost Price": 79,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OW17PS.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: 3365440229280,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 467432,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Toilette Spray (New Packaging) 90 ml",
		Gender: "Women",
		RETAIL: 100,
		"Cost Price": 71.69,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/PW3EDTS.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "90 ml",
		UPC: 3365440556386,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 425395,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Parfum Spray 30 ml",
		Gender: "Women",
		RETAIL: 60,
		"Cost Price": 80,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/opi1ozedps.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "30 ml",
		UPC: 3365440556300,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400133,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Toilette Spray (New Packaging) 30 ml",
		Gender: "Women",
		RETAIL: 55,
		"Cost Price": 56.44,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OPITS1.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "30 ml",
		UPC: 3365440003026,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400134,
		Name: "Opium by Yves Saint Laurent",
		Description:
			"Created by the design house of Yves Saint Laurent in 1977, Opium is classified as a refined, oriental, soft fragrance. This feminine scent begins with notes of mandarin and bergamot, then myrrh, jasmine and carnation. It is completed with a final note of Amber.",
		Brand: "Yves Saint Laurent",
		Title: "Eau De Toilette Spray (New Packaging) 50 ml",
		Gender: "Women",
		RETAIL: 82.5,
		"Cost Price": 75.28,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OPITS16.jpg",
		URL: "https://www.fragrancex.com/products/yves-saint-laurent/opium-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 446012,
		Name: "Organza by Givenchy",
		Description:
			"Launched by the design house of Givenchy in 1996, Organza is classified as a sharp, oriental, woody fragrance. This feminine scent possesses a blend of honeysuckle, amber, nutmeg, vanilla and gardenia. It is recommended for daytime wear.",
		Brand: "Givenchy",
		Title: "Eau De Parfum Spray (Tester) 50 ml",
		Gender: "Women",
		RETAIL: 77,
		"Cost Price": 25.88,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OW17T.jpg",
		URL: "https://www.fragrancex.com/products/givenchy/organza-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400154,
		Name: "Organza by Givenchy",
		Description:
			"Launched by the design house of Givenchy in 1996, Organza is classified as a sharp, oriental, woody fragrance. This feminine scent possesses a blend of honeysuckle, amber, nutmeg, vanilla and gardenia. It is recommended for daytime wear.",
		Brand: "Givenchy",
		Title: "Eau De Parfum Spray 50 ml",
		Gender: "Women",
		RETAIL: 94.5,
		"Cost Price": 44.4,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/ORG50PSW.jpg",
		URL: "https://www.fragrancex.com/products/givenchy/organza-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400148,
		Name: "Organza by Givenchy",
		Description:
			"Launched by the design house of Givenchy in 1996, Organza is classified as a sharp, oriental, woody fragrance. This feminine scent possesses a blend of honeysuckle, amber, nutmeg, vanilla and gardenia. It is recommended for daytime wear.",
		Brand: "Givenchy",
		Title: "Eau De Parfum Spray 100 ml",
		Gender: "Women",
		RETAIL: 95,
		"Cost Price": 43.87,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/W125394O.jpg",
		URL: "https://www.fragrancex.com/products/givenchy/organza-perfume?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 3274870212369,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 543387,
		Name: "Oscar by Oscar De La Renta",
		Description:
			"Launched by the design house of Oscar de la Renta in 1977. Its fragrant nature explores essences of bergamot, fern and vetiver. Blended with notes of cinnamon,ÃÂ carnation and moss, Oscar is a romantic type of fragrance.",
		Brand: "Oscar De La Renta",
		Title: "Shower Gel 200 ml",
		Gender: "Men",
		RETAIL: 35,
		"Cost Price": 5.5,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OM67BW.jpg",
		URL: "https://www.fragrancex.com/products/oscar-de-la-renta/oscar-cologne?src=drpshp",
		Quantity: 500,
		size: "200 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400169,
		Name: "Oscar by Oscar De La Renta",
		Description:
			"Launched by the design house of Oscar de la Renta in 1977. Its fragrant nature explores essences of bergamot, fern and vetiver. Blended with notes of cinnamon,ÃÂ carnation and moss, Oscar is a romantic type of fragrance.",
		Brand: "Oscar De La Renta",
		Title: "Eau De Toilette Spray 90 ml",
		Gender: "Men",
		RETAIL: 65,
		"Cost Price": 28,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/ODR90TSM1.jpg",
		URL: "https://www.fragrancex.com/products/oscar-de-la-renta/oscar-cologne?src=drpshp",
		Quantity: 500,
		size: "90 ml",
		UPC: null,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400184,
		Name: "Oscar by Oscar De La Renta",
		Description:
			"Launched by the design house of Oscar de la Renta in 1977, Oscar is classified as a refined, oriental, floral fragrance. This feminine scent possesses a blend of basil, jasmine, lavender and sandalwood. It is recommended for evening wear.",
		Brand: "Oscar De La Renta",
		Title: "Eau De Toilette Spray 100 ml",
		Gender: "Women",
		RETAIL: 87,
		"Cost Price": 27.83,
		Image_1:
			"https://img.fragrancex.com/images/products/sku/large/W134404O.jpg",
		URL: "https://www.fragrancex.com/products/oscar-de-la-renta/oscar-perfume?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 85715571007,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 400197,
		Name: "Oscar by Oscar De La Renta",
		Description:
			"Launched by the design house of Oscar de la Renta in 1977, Oscar is classified as a refined, oriental, floral fragrance. This feminine scent possesses a blend of basil, jasmine, lavender and sandalwood. It is recommended for evening wear.",
		Brand: "Oscar De La Renta",
		Title: "Eau De Toilette Spray 50 ml",
		Gender: "Women",
		RETAIL: 67,
		"Cost Price": 21.93,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/OSCTS16.jpg",
		URL: "https://www.fragrancex.com/products/oscar-de-la-renta/oscar-perfume?src=drpshp",
		Quantity: 500,
		size: "50 ml",
		UPC: 85715568007,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
	{
		SKU: 548622,
		Name: "Oscar by Oscar De La Renta",
		Description:
			"Launched by the design house of Oscar de la Renta in 1977, Oscar is classified as a refined, oriental, floral fragrance. This feminine scent possesses a blend of basil, jasmine, lavender and sandalwood. It is recommended for evening wear.",
		Brand: "Oscar De La Renta",
		Title: "Eau De Toilette Spray (Limited Edition) 100 ml",
		Gender: "Women",
		RETAIL: null,
		"Cost Price": 32,
		Image_1: "https://img.fragrancex.com/images/products/sku/large/oscle33.jpg",
		URL: "https://www.fragrancex.com/products/oscar-de-la-renta/oscar-perfume?src=drpshp",
		Quantity: 500,
		size: "100 ml",
		UPC: 3252550610858,
		catalog_time: "2024-06-30 08:19:29 EDT",
		supplier: "FragranceX",
	},
];
